language: c

os:
  - osx

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create -y -n test -c conda-forge python=3.5 gdcm
  - source activate test

script:
  - python -c 'import gdcm'
